description: Retrieve a specified eml/msg file directly from the email security gateway
  product.
id: Get Email From Email Gateway - Generic
inputs:
- description: The message ID received by the Email Security product.
  key: MessageID
  playbookInputQuery:
  required: false
  value: {}
- description: The Id of user.
  key: UserID
  playbookInputQuery:
  required: false
  value: {}
name: Get Email From Email Gateway - Generic
outputs:
- contextPath: File
  description: The MSG/EML File Entry ID
  type: string
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
      - "8"
      - "9"
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4601bd5d-21a9-4f61-8148-7efbd545c017
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 4601bd5d-21a9-4f61-8148-7efbd545c017
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 14daa7d5-080e-4db6-8bae-c43b3189df09
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 14daa7d5-080e-4db6-8bae-c43b3189df09
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 560
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      MessageID:
        complex:
          root: inputs.MessageID
      UserID:
        complex:
          root: inputs.UserID
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Retrieve Email Data from one of the Integrations of Gmail, Mail
        Listener v2, EWS O365, Microsoft Graph Mail.
      id: 31d44c85-5583-4826-8618-a09680af641e
      iscommand: false
      name: Get Email From Email Gateway - Agari
      playbookId: Get Email From Email Gateway - Agari
      type: playbook
      version: -1
    taskid: 31d44c85-5583-4826-8618-a09680af641e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1130,
          "y": 330
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      EmailTimestamp:
        complex:
          accessor: occurred
          root: incident
      MessageID:
        complex:
          root: inputs.MessageID
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Retrieve a specified eml/msg file directly from FireEye Email Security
        or Central Management.
      id: e99c1e30-b056-4a54-8123-d0b5df592312
      iscommand: false
      name: Get Email From Email Gateway - FireEye
      playbookId: Get Email From Email Gateway - FireEye
      type: playbook
      version: -1
    taskid: e99c1e30-b056-4a54-8123-d0b5df592312
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 200,
          "y": 360
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      MessageID:
        complex:
          root: inputs.MessageID
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Retrieve a specified eml/msg file directly from Mimecast.
      id: b0d5dc7f-ab2c-41c7-8a93-09322abf2648
      iscommand: false
      name: Get Email From Email Gateway - Mimecast
      playbookId: Get Email From Email Gateway - Mimecast
      type: playbook
      version: -1
    taskid: b0d5dc7f-ab2c-41c7-8a93-09322abf2648
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 690,
          "y": 360
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      MessageID:
        complex:
          root: inputs.MessageID
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Retrieve a specified eml/msg file directly from Proofpoint Protection
        Server.
      id: 2e412fff-3285-45fe-8522-a882c10006e7
      iscommand: false
      name: Get Email From Email Gateway - Proofpoint Protection Server
      playbookId: Get Email From Email Gateway - Proofpoint Protection Server
      type: playbook
      version: -1
    taskid: 2e412fff-3285-45fe-8522-a882c10006e7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -240,
          "y": 330
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 435,
        "width": 1750,
        "x": -240,
        "y": 190
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
