contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: This playbook will guide the user in the process of editing existing
  policy, the playbook will send a data collection form that will retrieve the relevant
  parameters for editing the existing rule.
id: PAN-OS edit policy
inputs:
- description: The email of the relevant security team for FW change management approval.
  key: SecurityTeamEmail
  playbookInputQuery:
  required: false
  value: {}
- description: The name of the relevant policy.
  key: rulename
  playbookInputQuery:
  required: false
  value: {}
name: PAN-OS edit policy
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fa6a958b-44d3-4166-885e-674d09d7f16c
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: fa6a958b-44d3-4166-885e-674d09d7f16c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": -280
        }
      }
  "1":
    form:
      description: 'Please provide the following paraments'
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Element to change?
        options: []
        optionsarg:
        - simple: source
        - simple: destination
        - simple: application
        - simple: action
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: 'Element value to be edit'
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: Rule position (should be the exact position as defined in Panorama)
        options: []
        optionsarg:
        - simple: post-rulebase
        - simple: pre-rulebase
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "3"
        label: ""
        labelarg:
          simple: Behavior
        options: []
        optionsarg:
        - simple: replace
        - simple: add
        - simple: remove
        placeholder: ""
        readonly: false
        required: false
        tooltip: Whether to replace, add, or remove the element_value from the current
          rule object value.
        type: singleSelect
      sender: ""
      title: Which parameters to edit in the policy?
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc:
      body:
        simple: 'Please provide the following parameters for editing the current policy'
      cc:
      format: ""
      methods:
      - email
      subject:
        simple: Parameters to edit in the policy
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
        simple: ${inputs.SecurityTeamEmail}
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This task query the user which object to modify in the current
        policy
      id: 1ebaf0ef-a356-4680-86cc-eb81d6514f81
      iscommand: false
      name: Which parameters to edit in the policy?
      type: collection
      version: -1
    taskid: 1ebaf0ef-a356-4680-86cc-eb81d6514f81
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 300,
          "y": 80
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0bf332bc-2864-43b9-8c0a-a56b17a00036
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 0bf332bc-2864-43b9-8c0a-a56b17a00036
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 860
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      behaviour:
        simple: ${Which parameters to edit in the policy?.Answers.3}
      element_to_change:
        simple: ${Which parameters to edit in the policy?.Answers.0}
      element_value:
        simple: ${Which parameters to edit in the policy?.Answers.1}
      pre_post:
        simple: ${Which parameters to edit in the policy?.Answers.2}
      rulename:
        simple: ${inputs.rulename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Edits a policy rule.
      id: 4c4448c3-5c73-403c-8f27-3bfd8d6a9f8f
      iscommand: true
      name: Edit current policy
      script: '|||panorama-edit-rule'
      type: regular
      version: -1
    taskid: 4c4448c3-5c73-403c-8f27-3bfd8d6a9f8f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 300,
          "y": 275
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: 99a4e7ee-635f-4a07-8d89-f76259cabbbf
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 99a4e7ee-635f-4a07-8d89-f76259cabbbf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 680
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Commit the PAN-OS Panorama or Firewall configuration.\nIf specified
        as Panorama, it also pushes the Policies to the specified Device Group in
        the instance.
      id: 97f707a9-2681-45e9-8d89-f5c137e452aa
      iscommand: false
      name: PAN-OS Commit Configuration
      playbookId: PAN-OS Commit Configuration
      type: playbook
      version: -1
    taskid: 97f707a9-2681-45e9-8d89-f5c137e452aa
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 480
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      behaviour:
        simple: ${Which parameters to edit in the policy?.Answers.3}
      element_to_change:
        simple: ${Which parameters to edit in the policy?.Answers.0}
      element_value:
        simple: ${Which parameters to edit in the policy?.Answers.1}
      rulename:
        simple: ${inputs.rulename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Edits a policy rule.
      id: 05ecdd70-001f-4d8d-8e7f-4c1f6a612df4
      iscommand: true
      name: Edit current policy
      script: '|||panorama-edit-rule'
      type: regular
      version: -1
    taskid: 05ecdd70-001f-4d8d-8e7f-4c1f6a612df4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -200,
          "y": 275
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.name
                    operator: containsGeneral
                    right:
                      value:
                        simple: Panorama
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: panorama
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.name
                    operator: containsGeneral
                    right:
                      value:
                        simple: Pan-os
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: Pan-os
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Pan-os:
      - "11"
      panorama:
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'This task which instance is available Panorama or Pan-os?'
      id: e884484a-7226-4a09-8833-bdef0f6ec1c9
      iscommand: false
      name: Panorama or Pan-os?
      type: condition
      version: -1
    taskid: e884484a-7226-4a09-8833-bdef0f6ec1c9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": -130
        }
      }
  "11":
    form:
      description: 'Please provide the following paraments'
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Element to change?
        options: []
        optionsarg:
        - simple: source
        - simple: destination
        - simple: application
        - simple: action
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: 'Element value to be edit'
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: Behavior
        options: []
        optionsarg:
        - simple: replace
        - simple: add
        - simple: remove
        placeholder: ""
        readonly: false
        required: false
        tooltip: Whether to replace, add, or remove the element_value from the current
          rule object value.
        type: singleSelect
      sender: ""
      title: Which parameters to edit in the policy?
      totalanswers: 0
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc:
      body:
        simple: 'Please provide the following parameters for editing the current policy'
      cc:
      format: ""
      methods:
      - email
      subject:
        simple: Parameters to edit in the policy
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
        simple: ${inputs.SecurityTeamEmail}
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This task query the user which object to modify in the current
        policy
      id: 824b8ed7-6005-4098-858f-168851f95340
      iscommand: false
      name: Which parameters to edit in the policy?
      type: collection
      version: -1
    taskid: 824b8ed7-6005-4098-858f-168851f95340
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": -200,
          "y": 80
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_11_Pan-os": 0.64
    },
    "paper": {
      "dimensions": {
        "height": 1205,
        "width": 880,
        "x": -200,
        "y": -280
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
