id: Phishing Alerts - Check Severity
version: -1
name: Phishing Alerts - Check Severity
description: |-
  Calculate and assign the incident severity based on the highest returned severity level from the following calculations:

  Email security alert action
  DBotScores of indicators
  Critical assets
  Email authenticity
  Current incident severity
  Microsoft Headers
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d4f8035a-a3cb-4f25-8db8-07531da13c95
    type: start
    task:
      id: d4f8035a-a3cb-4f25-8db8-07531da13c95
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 220,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e1ada877-c9e9-4cb2-8471-b261e80e547c
    type: regular
    task:
      id: e1ada877-c9e9-4cb2-8471-b261e80e547c
      version: -1
      name: Assign to analyst
      description: Assign the incident to an analyst based on the analyst's organizational
        role.
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      onCall:
        complex:
          root: inputs.OnCall
      roles:
        complex:
          root: inputs.escalationRole
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 3263812e-eff6-4715-88b1-24b07dab62ab
    type: playbook
    task:
      id: 3263812e-eff6-4715-88b1-24b07dab62ab
      version: -1
      name: Calculate Severity - Generic v2
      description: |-
        Calculate and assign the incident severity based on the highest returned severity level from the following calculations:
        - DBotScores of indicators
        - Critical assets
        - Email authenticity
        - Current incident severity
        - Microsoft Headers
      playbookName: Calculate Severity - Generic v2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      Account:
        complex:
          root: Account
          transformers:
          - operator: uniq
      CriticalEndpoints:
        simple: admin
      CriticalGroups:
        simple: admins,administrators
      CriticalUsers:
        simple: admin,administrator
      DBotScore:
        complex:
          root: DBotScore
      EmailAuthenticityCheck:
        complex:
          root: inputs.AuthenticityCheck
      Endpoint:
        complex:
          root: Endpoint
          transformers:
          - operator: uniq
      MicrosoftHeadersSeverityCheck:
        complex:
          root: inputs.MicrosoftHeadersSeverityCheck
    separatecontext: true
    loop:
      iscommand: false
      scriptArguments:
        Account:
          complex:
            root: Account
            transformers:
            - operator: uniq
        CriticalEndpoints:
          simple: admin
        CriticalGroups:
          simple: admins,administrators
        CriticalUsers:
          simple: admin,administrator
        DBotScore:
          complex:
            root: DBotScore
        EmailAuthenticityCheck:
          complex:
            root: Email
            accessor: AuthenticityCheck
            transformers:
            - operator: uniq
        Endpoint:
          complex:
            root: Endpoint
            transformers:
            - operator: uniq
        MicrosoftHeadersSeverityCheck:
          complex:
            root: Email
            accessor: MicrosoftHeadersSeverityCheck
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -17.5,
          "y": 420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 6fd28512-0f21-42e9-8007-2c55feb4d231
    type: regular
    task:
      id: 6fd28512-0f21-42e9-8007-2c55feb4d231
      version: -1
      name: Set incident severity to "High"
      description: Sets the incident severity to "Critical".
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      severity:
        simple: critical
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: abfc4858-a19a-48a5-852d-8d0d4ab19cfa
    type: condition
    task:
      id: abfc4858-a19a-48a5-852d-8d0d4ab19cfa
      version: -1
      name: Determine incident severity
      description: Determines the severity level based on the highest result of all
        severity calculations.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      - "5"
      High:
      - "3"
      - "1"
    separatecontext: false
    conditions:
    - label: High
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: Splunk
                accessor: DetectedUsers
                transformers:
                - operator: append
                  args:
                    item:
                      value:
                        simple: Splunk.DetectedExternalIPs
                      iscontext: true
                - operator: append
                  args:
                    item:
                      value:
                        simple: Splunk.DetectedExternalHosts
                      iscontext: true
                - operator: append
                  args:
                    item:
                      value:
                        simple: QRadar.DetectedUsers
                      iscontext: true
                - operator: append
                  args:
                    item:
                      value:
                        simple: QRadar.DetectedExternalIPs
                      iscontext: true
                - operator: append
                  args:
                    item:
                      value:
                        simple: QRadar.DetectedExternalHosts
                      iscontext: true
                - operator: append
                  args:
                    item:
                      value:
                        simple: PANWHunting.DetectedUsers
                      iscontext: true
                - operator: append
                  args:
                    item:
                      value:
                        simple: PANWHunting.DetectedExternalIPs
                      iscontext: true
                - operator: append
                  args:
                    item:
                      value:
                        simple: PANWHunting.DetectedExternalHosts
                      iscontext: true
            iscontext: true
        - operator: notIn
          left:
            value:
              complex:
                root: incident
                accessor: alertaction
            iscontext: true
          right:
            value:
              complex:
                root: inputs.blockedAlertActionValue
            iscontext: true
    view: |-
      {
        "position": {
          "x": 220,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 9c84f851-6b87-4ef9-83cc-c12ff35780d5
    type: regular
    task:
      id: 9c84f851-6b87-4ef9-83cc-c12ff35780d5
      version: -1
      name: Assign to analyst
      description: Assign the incident to an analyst based on the analyst's organizational
        role.
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      onCall:
        complex:
          root: inputs.OnCall
      roles:
        complex:
          root: inputs.Role
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -420,
          "y": 390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: d88d7bb0-bb26-4c54-8882-363f5b07d59b
    type: regular
    task:
      id: d88d7bb0-bb26-4c54-8882-363f5b07d59b
      version: -1
      name: Assign to analyst
      description: |-
        Assign analyst to incident.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
        current: The user that executed the command
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      onCall:
        complex:
          root: inputs.OnCall
      roles:
        complex:
          root: inputs.escalationRole
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 220,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 3e5ca5e9-9526-496f-8872-df76f93280fc
    type: regular
    task:
      id: 3e5ca5e9-9526-496f-8872-df76f93280fc
      version: -1
      name: Set incident severity to "Critical"
      description: Optionally increases the incident severity to the new value if
        it is greater than the existing severity.
      scriptName: IncreaseIncidentSeverity
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      severity:
        simple: Critical
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: b9214825-23f8-4842-8793-bc8db97b30ec
    type: regular
    task:
      id: b9214825-23f8-4842-8793-bc8db97b30ec
      version: -1
      name: Sensitive mailbox phishing attempt notification
      description: Sends an email regarding the findings of the sensitive mailboxes
        check.
      script: '|||send-mail'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      body:
        simple: |
          XSOAR has identified a suspicious email that was sent to one or more of the organization's sensitive mailboxes.
          The incident severity has been raised to Critical.

          The following recipients where detected:
          Email Subject: ${incident.emailsubject}
          Email TO: ${incident.emailto}
          Email CC: ${incident.emailcc}
          Email BCC: ${incident.emailbcc}
          Message ID: ${incident.emailmessageid}
          XSOAR
      subject:
        simple: Sensitive mailbox phishing attempt - incident ${incident.name}
      to:
        complex:
          root: inputs.SOCEmailAddress
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 3eb8b996-4f13-41c5-8a5b-940a4eafaa97
    type: title
    task:
      id: 3eb8b996-4f13-41c5-8a5b-940a4eafaa97
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 220,
          "y": 1340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: ffef0224-3867-4770-8887-228a30918aa3
    type: condition
    task:
      id: ffef0224-3867-4770-8887-228a30918aa3
      description: This task checks if the recipient was found under CriticalAssets
        or in a provided list.
      version: -1
      name: Check if the recipient is in the sensitive mailboxes list
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      SensitiveMailbox:
      - "7"
    separatecontext: false
    conditions:
    - label: SensitiveMailbox
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: CriticalAssets
            iscontext: true
        - operator: inList
          left:
            value:
              complex:
                root: inputs.EmailTo
            iscontext: true
          right:
            value:
              complex:
                root: inputs.SensitiveMailboxesList
            iscontext: true
    view: |-
      {
        "position": {
          "x": 220,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "11_7_SensitiveMailbox": 0.52,
      "4_3_High": 0.66
    },
    "paper": {
      "dimensions": {
        "height": 1345,
        "width": 1650,
        "x": -420,
        "y": 60
      }
    }
  }
inputs:
- key: Role
  value: {}
  required: false
  description: The default role to assign the incident to.
  playbookInputQuery:
- key: escalationRole
  value: {}
  required: false
  description: A higher tier role to assign the incident to.
  playbookInputQuery:
- key: OnCall
  value: {}
  required: false
  description: Set to true to assign only a user that is currently on shift. Requires.
  playbookInputQuery:
- key: AuthenticityCheck
  value: {}
  required: false
  description: 'Indicates the email authenticity resulting from the EmailAuthenticityCheck
    script. Possible values are: Pass, Fail, Suspicious, and Undetermined.'
  playbookInputQuery:
- key: MicrosoftHeadersSeverityCheck
  value: {}
  required: false
  description: The value is set by the "Process Microsoft's Anti-Spam Headers" Playbook,
    which calculates the severity after processing the PCL, BCL and PCL values inside
    Microsoft's headers.
  playbookInputQuery:
- key: SOCEmailAddress
  value: {}
  required: false
  description: The SOC email address to set in case the playbook handles an Email
    Security alert.
  playbookInputQuery:
- key: EmailTo
  value: {}
  required: false
  description: The email recipient.
  playbookInputQuery:
- key: blockedAlertActionValue
  value: {}
  required: false
  description: List of optional values the email security device returns for blocked\denied\etc.
    emails.
  playbookInputQuery:
- key: SensitiveMailboxesList
  value: {}
  required: false
  description: A list that contains the organization sensitive mailboxes.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.0.0
